"""Initial migration

Revision ID: 8cf320b2c8b4
Revises: 
Create Date: 2025-11-14 22:58:46.140702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf320b2c8b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_master_id'), 'product_master', ['id'], unique=False)
    op.create_index(op.f('ix_product_master_product_code'), 'product_master', ['product_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROCUREMENT_OFFICER', 'WAREHOUSE_MANAGER', 'ACCOUNTANT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_type', sa.Enum('PARTNER', 'RM', 'PM', 'MANUFACTURER', name='vendortype'), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_table('medicine_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_code', sa.String(length=50), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('pack_size', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_master_id'), 'medicine_master', ['id'], unique=False)
    op.create_index(op.f('ix_medicine_master_medicine_code'), 'medicine_master', ['medicine_code'], unique=True)
    op.create_table('pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_number', sa.String(length=50), nullable=False),
    sa.Column('pi_date', sa.Date(), nullable=False),
    sa.Column('partner_vendor_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pi_id'), 'pi', ['id'], unique=False)
    op.create_index(op.f('ix_pi_pi_number'), 'pi', ['pi_number'], unique=True)
    op.create_table('dispatch_advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=50), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity_dispatched', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_advice_dispatch_number'), 'dispatch_advice', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_dispatch_advice_id'), 'dispatch_advice', ['id'], unique=False)
    op.create_table('eopa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eopa_number', sa.String(length=50), nullable=False),
    sa.Column('eopa_date', sa.Date(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='eopastatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_id')
    )
    op.create_index(op.f('ix_eopa_eopa_number'), 'eopa', ['eopa_number'], unique=True)
    op.create_index(op.f('ix_eopa_id'), 'eopa', ['id'], unique=False)
    op.create_table('material_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id')
    )
    op.create_index(op.f('ix_material_balance_id'), 'material_balance', ['id'], unique=False)
    op.create_table('pi_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pi_items_id'), 'pi_items', ['id'], unique=False)
    op.create_table('eopa_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eopa_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eopa_id'], ['eopa.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eopa_items_id'), 'eopa_items', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('po_type', sa.Enum('RM', 'PM', 'FG', name='potype'), nullable=False),
    sa.Column('eopa_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['eopa_id'], ['eopa.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('warehouse_grn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=False),
    sa.Column('dispatch_advice_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_advice_id'], ['dispatch_advice.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_grn_grn_number'), 'warehouse_grn', ['grn_number'], unique=True)
    op.create_index(op.f('ix_warehouse_grn_id'), 'warehouse_grn', ['id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_material_receipts_receipt_number'), 'material_receipts', ['receipt_number'], unique=True)
    op.create_table('po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_master.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_items_id'), 'po_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_items_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_material_receipts_receipt_number'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_warehouse_grn_id'), table_name='warehouse_grn')
    op.drop_index(op.f('ix_warehouse_grn_grn_number'), table_name='warehouse_grn')
    op.drop_table('warehouse_grn')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_eopa_items_id'), table_name='eopa_items')
    op.drop_table('eopa_items')
    op.drop_index(op.f('ix_pi_items_id'), table_name='pi_items')
    op.drop_table('pi_items')
    op.drop_index(op.f('ix_material_balance_id'), table_name='material_balance')
    op.drop_table('material_balance')
    op.drop_index(op.f('ix_eopa_id'), table_name='eopa')
    op.drop_index(op.f('ix_eopa_eopa_number'), table_name='eopa')
    op.drop_table('eopa')
    op.drop_index(op.f('ix_dispatch_advice_id'), table_name='dispatch_advice')
    op.drop_index(op.f('ix_dispatch_advice_dispatch_number'), table_name='dispatch_advice')
    op.drop_table('dispatch_advice')
    op.drop_index(op.f('ix_pi_pi_number'), table_name='pi')
    op.drop_index(op.f('ix_pi_id'), table_name='pi')
    op.drop_table('pi')
    op.drop_index(op.f('ix_medicine_master_medicine_code'), table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_id'), table_name='medicine_master')
    op.drop_table('medicine_master')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_master_product_code'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_id'), table_name='product_master')
    op.drop_table('product_master')
    # ### end Alembic commands ###
